name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # See: https://github.com/actions/cache/blob/main/examples.md#node---npm
#      - name: Use Node.js cache
#        uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-

      # `--prefer-offline` gives cache priority
      - name: Install dependencies
#        run: npm install --prefer-offline --frozen-lockfile
        run: npm install

      - name: Lint application
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Deploy documentation to Github pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: .
          publish_branch: gh-pages
          force_orphan: false
